[package]
name = "gif"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "render"
path = "src/main.rs"

[dependencies]
eyre = "0.6.12"

# render dependencies
minifb = "0.27.0"
clap = { version = "4.5.20", features = ["derive"] }


